### ISSUE TITLE
karma is deprecated, wondering do we have any migration plan for this sample app? 

### ISSUE THREAD

**Issue by longshengzhou** [SAP/openui5-sample-app#199]
Karma deprecation announcement: https://github.com/karma-runner/karma#karma-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes

**Comment by flovogt** [comment]
Hi @longshengzhou, thanks a lot for opening this issue here. The team does already discuss possible options to replace `karma`. We'll post further updates here.

**Comment by flovogt** [comment]
@longshengzhou We have removed the karma setup and migrated the app to the https://www.npmjs.com/package/ui5-test-runner setup
