### ISSUE TITLE
Un-themed content briefly shows with a flicker...

### ISSUE THREAD

**Issue by js1972** [SAP/openui5-sample-app#2]
I've cloned this app and started the server with grunt. When I navigate to localhost:8080 in the browser the page briefly flashed with plain html controls in the top left most corner and then snaps into the proper themed look... It only lasts for a split second but happens everytime I refresh the page.

This issue does not happen when I use a real SAP Fiori app served from our ABAP system, nor does it happen with my own UI5 apps served with grunt-contrib-connect.

With a little bit of playing around I've found that the culprit is the boot attribute: "data-sap-ui-preload="async"".
If this exists - the app looks to load faster however there is a delay before the styling is applied and hence you see an ugly initial flash of the unstyled controls.

When you remove this boot attribute you no longer see that uglyness but that load time is longer.

I also see this message in the console as well that I don't usually see: "ThemeCheck: Theme not yet applied".

Is there a way that the CSS can be loaded first?

**Comment by akudev** [comment]
Hi,
actually this is not a specific issue for this app, I also see it happening with the SDK, and I 'm not aware of the official position on this - is it accepted? Is it being addressed? Or does nobody care? I'll investigate (internal reference: 1570017563).

Regards
Andreas

**Comment by js1972** [comment]
Thanks Andreas... Its pretty ugly. Kind of rules out the use of preload component files for me...

**Comment by matz3** [comment]
library.css files can also be loaded directly using <link> tags with an ID `sap-ui-theme-{library-name}`. The core will then not include the files again.
This should solve the flickering issue (when using async loading) and make the app load faster.

```html
<link rel="stylesheet" type="text/css" id="sap-ui-theme-sap.ui.core"
	href="resources/sap/ui/core/themes/sap_bluecrystal/library.css" />
<link rel="stylesheet" type="text/css" id="sap-ui-theme-sap.m"
	href="resources/sap/m/themes/sap_bluecrystal/library.css" />
```

**Comment by akudev** [comment]
Is this something we should also apply, e.g. in the Demokit?

**Comment by js1972** [comment]
Will try this... If it stops the ugly flash of un-themed content then maybe this should be added to the openui5-sample app as a best practice....






On Mon, Feb 2, 2015 at 6:12 AM -0800, "Matthias Oßwald" <notifications@github.com> wrote:












library.css files can also be loaded directly using  tags with an ID sap-ui-theme-{library-name}. The core will then not include the files again.

This should solve the flickering issue (when using async loading) and make the app load faster.

<link rel="stylesheet" type="text/css" id="sap-ui-theme-sap.ui.core"
    href="resources/sap/ui/core/themes/sap_bluecrystal/library.css" />
<link rel="stylesheet" type="text/css" id="sap-ui-theme-sap.m"
    href="resources/sap/m/themes/sap_bluecrystal/library.css" />

**Comment by js1972** [comment]
Directly loading the library.css files does indeed fix the flickering issue. You now just see the standard pale blue background before the page renders which is much better...
My little test app is so small any speed difference is not that noticeable.
Might be a good idea to link to this app as a best practices / ideas sort of thing from the openui5.org page or the github page...

**Comment by derwaldgeist** [comment]
It's pretty annoying that this is still the case after all those years...
