### ISSUE TITLE
[question] How to add additional UI5 dependencies

### ISSUE THREAD

**Issue by t1mb0b** [SAP/openui5-sample-app#27]
Thank for putting this together, this is great!

I am wondering if there are any instructions, or possibly a blog post you could point me to regarding how to add additional UI5 components (i.e Form, SimpleFrom, and all the others) to the bower config? I can change the index.html to point to the CDN 'sap-ui-core.js', though I am not sure if there is a better way to keep everything contained within this build.
 
Also, once the 'dist' folder has been completed, how does one go about deploying this to GW? I like the idea of being able to build FLP-ready apps outside of using WebIDE.

Thanks again!

**Comment by matz3** [comment]
You can find the bower packages of the OpenUI5 libraries here:
https://github.com/openui5?q=packaged-

Depending on the controls you want to use, you need to include those libraries to your list of bower dependencies (e.g. [openui5/sap.ui.layout](https://github.com/openui5/packaged-sap.ui.layout) for "Form" / "SimpleForm").

Deployment is not part of this example project, so I'm afraid I can't help here.
