### ISSUE TITLE
ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by se-wo** [SAP/openui5-sample-app#28]
The app is not runnable using the commands provided in the Readme.
I cloned the repository, executed npm install and grunt serve. May have to do with OpenUi5 version 1.54 that is installed by default.
Opening localhost:8080 results in the following errors:

ReferenceError: jQuery is not defined sap-ui-core.js%20line%2055%20%3E%20eval:1:1
	<anonym> http://localhost:8080/resources/sap/ui/core/library-preload.js:1:1
	execModule http://localhost:8080/resources/sap-ui-core.js:55:8353
	requireModule http://localhost:8080/resources/sap-ui-core.js:55:6926
	requireSync http://localhost:8080/resources/sap-ui-core.js:55:12062
	<anonym> http://localhost:8080/resources/sap-ui-core.js:60:5814

TypeError: sap.ui.getCore is not a function localhost:8080:19:3
	<anonym> http://localhost:8080/:19:3

**Comment by ivanlynch** [comment]
I have the same issue :(

**Comment by matz3** [comment]
Thanks for letting us know 👍  The `1.54.0` bower version is indeed broken.
We are looking into it and hope to provide a solution in the next days.

**Comment by petermuessig** [comment]
@matz3 `1.54.0` and `1.54.1` are affected, pull request has been created for grunt-openui5: https://github.com/SAP/grunt-openui5/pull/65

**Comment by matz3** [comment]
Short update:
I've re-created the bower releases `1.54.0`, `1.54.1` and `1.54.2` with the updated `grunt-openui5` plugin ([v0.13.0](https://github.com/SAP/grunt-openui5/releases/tag/0.13.0)).
With this the bootstrap should be fixed. Please let us know if there are still some issues w.r.t. the 1.54 release.
