### ISSUE TITLE
Minified sources?

### ISSUE THREAD

**Issue by js1972** [SAP/openui5-sample-app#3]
This is not really an issue with this app but I was just wondering why Google Pagespeed would say the openui5 sources used by this app are not minified? I thought OpenUI5 only used the "-dbg" prefix for the un-minified files. Maybe the Bower versions are un-minified?

**Comment by akudev** [comment]
Hi,
well... the sources in the Bower repo are unminified, but let's check with the developer who created it (next week).

Regards
Andreas

**Comment by matz3** [comment]
The single source files are currently not minified in the bower release. However, the files inside the `library-preload.json` files are minified. If running in dev mode the source files are loaded, so there isn't really a need to have every single file minimized.

**Comment by js1972** [comment]
Thx
