### ISSUE TITLE
Error with ui5 serve -o index.html

### ISSUE THREAD

**Issue by AxxlFoley** [SAP/openui5-sample-app#41]
When executing 

ui5 serve -o index.html 

I get the following error:

Error: Invalid specification version defined for project openui5-sample-app: 1.0. The currently only allowed version is "0.1"
    at ProjectPreprocessor.configureProject (....AppData\Roaming\npm\node_modules\@ui5\cli\node_modules\@ui5\project\lib\projectPreprocessor.js:122:10)
    at <anonymous>

**Comment by RandomByte** [comment]
Hey, you'll have to update your globally installed UI5 CLI by executing `npm install -g @ui5/cli`. See https://github.com/SAP/ui5-tooling/blob/master/docs/updates/migrate-v1.md#how-to-upgrade

We'll improve the error message to point out that your installation might be outdated 👍

**Comment by RandomByte** [comment]
Just checked and in newer releases of the UI5 CLI the error message already reads:  
`Invalid specification version defined for project xx: yy. See https://github.com/SAP/ui5-project/blob/master/docs/Configuration.md#specification-versions`. Which should help figuring this out.
