### ISSUE TITLE
Component pre-loading - when is it better?

### ISSUE THREAD

**Issue by js1972** [SAP/openui5-sample-app#5]
I notice that when playing with this application and changing it from using a component preload file or not there is little difference in loading time. In fact without component preloading is slightly faster (it also doesn't have the flicker that I mentioned in another issue).

So my question is - when is it best practice to use component preloading? Do you only get a benefit when your app has lots of views to avoid all the ajax requests..? Or is it something we should always aim to do noting that the underlying framework will improve and optimise things...

**Comment by matz3** [comment]
Bundling of multiple files is something you should always do to optimize an application.
In this case, it doesn't reduce the HTTP requests that much, therefore it is not a big difference. But if you have ~20 files in your component, it will boost the performance a lot (more than just uglifying all the single files).
Furthermore the sap-ui-core.js from the bower release is not yet fully optimized (see https://github.com/SAP/openui5/issues/276). If you use the CDN version from https://openui5.hana.ondemand.com/resources/sap-ui-core.js you should get different results.

**Comment by js1972** [comment]
Thankyou - as I expected - the preload files become more important the bigger your app is.
