### ISSUE TITLE
Usage of bootstrap tags to load Component

### ISSUE THREAD

**Issue by js1972** [SAP/openui5-sample-app#7]
I just wondering if its still good practice to use:

```
data-sap-ui-rootComponent="todo"
data-sap-ui-xx-rootComponentNode="root"
```

... to load the Component. I notice that there is no mention of this in the beta release of OpenUI5 1.30. Its not used in the 1.28 best practice apps (master details and worklist) either.

Maybe the direction is still undecided here...

**Comment by matz3** [comment]
Yes, you are right. Using an script to initialize a ComponentContainer manually is in fact the current way to go (especially as the "xx" configuration is actually "internal").

**Comment by js1972** [comment]
Great thanks for the info.
