### ISSUE TITLE
Clear completed ({/completedCount})

### ISSUE THREAD

**Issue by ibewugb** [SAP/openui5-sample-app#8]
There is one small issue: Clear completed ({/completedCount})

The binding is not running right here.

**Comment by matz3** [comment]
Thanks for reporting! I actually broke this with e17a055a28304f673f576d47f96d22cd40d7bca5 as the `sap-ui-bindingSyntax` configuration (without `-xx-`) was only introduced in 1.28.

I just updated all dependencies to be up to date again :+1:
