### ISSUE TITLE
How to start a new UI5 project?

### ISSUE THREAD

**Issue by FnEsc** [SAP/openui5-sample-app#95]
I get it that I can check out the sample app to learn UI5 quickly.
What's more, I'd like to know how to start a new UI5 project with ui5-cli or ui5-tooling or npm with my DIY project name/package name?
BTW, I'm using vs code instead of WebIDE.

**Comment by tobiasso85** [comment]
Hi @FnEsc and welcome :)

It depends pretty much on how you can best learn/develop.
Some like to start from the green field others adapt existing resources until they fit their needs.

The openui5-sample-app gives you some insights on how a UI5 app looks a like, the structure of the project and how it all connects.

I definitely recommend to do the UI5 course:
https://open.sap.com/courses/ui51

The ui5-cli is an essential part of the UI5 Tooling
Using ui5-cli you can use it to add the dependencies required, ini, build and serve your project
https://sap.github.io/ui5-tooling/pages/GettingStarted/

For VSCode there is also:
https://blogs.sap.com/2020/06/22/sap-fiori-tools-is-generally-available.-increase-the-efficiency-of-developing-sap-fiori-elements-apps/

Scaffolding is also available using:
https://blogs.sap.com/2019/02/05/introducing-the-easy-ui5-generator/

Regards
Tobias

Related: https://github.com/SAP/ui5-tooling/issues/40

**Comment by FnEsc** [comment]
Hi @tobiasso85 , so glad to see you.

This helps me a lot, it reminds me of "generator-easy-ui5"! And I can use it with ui5-cli.

```sh
npm install -g yo generator-easy-ui5
yo easy-ui5
cd <project name>
npm start # it is the same as "ui5 serve --config=uimodule/ui5.yaml  --open index.html" in package.json
ui5 serve --config=uimodule/ui5.yaml
ui5 use sapui5@latest --config=uimodule/ui5.yaml
```

In this time, I found that it's better for me to learn/develop sapui5 in freestyle rather than fiori elements templates. It's so cool for newers (like me) to learn sap. 

BRs,
FnEsc
